apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-airflow-config
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
data:
  AIRFLOW__CORE__EXECUTOR: "CeleryExecutor"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}"
  AIRFLOW__CELERY__BROKER_URL: "redis://:$(REDIS_PASSWORD)@{{ .Values.redis.host }}:{{ .Values.redis.port }}/0"
  AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ .Values.postgresql.host }}:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}"
  
  # Core settings
  AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
  AIRFLOW__CORE__PLUGINS_FOLDER: "/opt/airflow/plugins"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__EXPOSE_CONFIG: "false"
  AIRFLOW__CORE__FERNET_KEY: "$(AIRFLOW_FERNET_KEY)"
  
  # Webserver settings
  AIRFLOW__WEBSERVER__BASE_URL: "http://localhost:8080"
  AIRFLOW__WEBSERVER__SECRET_KEY: "$(AIRFLOW_SECRET_KEY)"
  AIRFLOW__WEBSERVER__WORKERS: "4"
  AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL: "30"
  AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: "120"
  
  # Scheduler settings
  AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC: "5"
  AIRFLOW__SCHEDULER__SCHEDULER_HEALTH_CHECK_THRESHOLD: "30"
  AIRFLOW__SCHEDULER__PARSING_PROCESSES: "2"
  AIRFLOW__SCHEDULER__DAG_FILE_PROCESSOR_TIMEOUT: "50"
  
  # Logging settings
  AIRFLOW__LOGGING__BASE_LOG_FOLDER: "/opt/airflow/logs"
  AIRFLOW__LOGGING__DAG_PROCESSOR_MANAGER_LOG_LOCATION: "/opt/airflow/logs/dag_processor_manager/dag_processor_manager.log"
  AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT: "8793"
  
  # API settings
  AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.basic_auth"
  
  # Email settings
  AIRFLOW__EMAIL__EMAIL_BACKEND: "airflow.utils.email.send_email_smtp" 