apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-airflow-config
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
data:
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://{{ .Values.security.postgresql.username }}:$(POSTGRES_PASSWORD)@{{ .Release.Name }}-pgbouncer:{{ .Values.network.pgbouncer.port }}/{{ .Values.security.postgresql.database }}
  AIRFLOW__CELERY__BROKER_URL: redis://:$(REDIS_PASSWORD)@{{ .Release.Name }}-redis-master:{{ .Values.network.redis.port }}/0
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://{{ .Values.security.postgresql.username }}:$(POSTGRES_PASSWORD)@{{ .Release.Name }}-pgbouncer:{{ .Values.network.pgbouncer.port }}/{{ .Values.security.postgresql.database }}
  AIRFLOW__WEBSERVER__SECRET_KEY: $(AIRFLOW_SECRET_KEY)
  AIRFLOW__CORE__FERNET_KEY: $(AIRFLOW_FERNET_KEY)
  AIRFLOW__WEBSERVER__BASE_URL: https://{{ .Values.openshift.route.host | default (printf "%s-airflow.%s" .Release.Name .Release.Namespace) }}
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC: "10"
  AIRFLOW__CELERY__WORKER_CONCURRENCY: "16"
  AIRFLOW__WEBSERVER__WORKERS: "2"
  AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL: "30"
  AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: "120"
  AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
  AIRFLOW__LOGGING__DAG_PROCESSOR_MANAGER_LOG_LOCATION: /opt/airflow/logs/dag_processor_manager/dag_processor_manager.log
  AIRFLOW__SCHEDULER__CHILD_PROCESS_LOG_DIRECTORY: /opt/airflow/logs/scheduler
  AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
  AIRFLOW__API__AUTH_BACKEND: airflow.api.auth.backend.basic_auth
  AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
  AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins 