apiVersion: {{ template "airflow.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ .Release.Name }}-triggerer
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: triggerer
spec:
  replicas: {{ .Values.triggerer.replicas }}
  selector:
    matchLabels:
      {{- include "airflow.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: triggerer
  template:
    metadata:
      labels:
        {{- include "airflow.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: triggerer
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.openshift.securityContext }}
      securityContext:
        runAsUser: {{ .runAsUser }}
        runAsGroup: {{ .runAsGroup }}
        fsGroup: {{ .fsGroup }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-airflow
      containers:
        - name: triggerer
          image: "{{ .Values.images.triggerer.repository }}:{{ .Values.images.triggerer.tag }}"
          imagePullPolicy: {{ .Values.images.triggerer.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-airflow-config
            - secretRef:
                name: {{ .Release.Name }}-airflow-secrets
          resources:
            {{- toYaml .Values.triggerer.resources | nindent 12 }}
          volumeMounts:
            - name: logs
              mountPath: /opt/airflow/logs
            - name: dags
              mountPath: /opt/airflow/dags
            - name: plugins
              mountPath: /opt/airflow/plugins
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - "airflow jobs check --job-type TriggererJob --hostname $(hostname)"
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - "airflow jobs check --job-type TriggererJob --hostname $(hostname)"
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-logs
        - name: dags
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-dags
        - name: plugins
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-plugins
      {{- with .Values.triggerer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.triggerer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.triggerer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 