apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-logs
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.logs.size }}
  {{- if .Values.storage.logs.storageClass }}
  storageClassName: {{ .Values.storage.logs.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-dags
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.dags.size }}
  {{- if .Values.storage.dags.storageClass }}
  storageClassName: {{ .Values.storage.dags.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-plugins
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.plugins.size }}
  {{- if .Values.storage.plugins.storageClass }}
  storageClassName: {{ .Values.storage.plugins.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-backup
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.backup.size }}
  {{- if .Values.storage.backup.storageClass }}
  storageClassName: {{ .Values.storage.backup.storageClass }}
  {{- end }}