{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-airflow
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
---
apiVersion: {{ template "airflow.rbac.apiVersion" . }}
kind: Role
metadata:
  name: {{ .Release.Name }}-airflow
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - pods/log
      - pods/exec
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
---
apiVersion: {{ template "airflow.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-airflow
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-airflow
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-airflow
    namespace: {{ .Values.common.namespace }}
{{- end }} 