apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-airflow-secrets
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.security.postgresql.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.security.postgresql.password | quote }}
  REDIS_PASSWORD: {{ .Values.security.redis.password | quote }}
  AIRFLOW_SECRET_KEY: {{ .Values.security.webserverSecretKey | quote }}
  AIRFLOW_FERNET_KEY: {{ .Values.security.fernetKey | quote }}
  AIRFLOW_WWW_USER_USERNAME: {{ .Values.security.webserverCredentials.username | quote }}
  AIRFLOW_WWW_USER_PASSWORD: {{ .Values.security.webserverCredentials.password | quote }} 