apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-airflow-secrets
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  # PostgreSQL credentials
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  
  # Redis credentials
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  
  # Airflow credentials
  AIRFLOW_SECRET_KEY: {{ .Values.airflow.secretKey | quote }}
  AIRFLOW_FERNET_KEY: {{ .Values.airflow.fernetKey | quote }}
  AIRFLOW_WWW_USER_USERNAME: {{ .Values.airflow.webserver.username | quote }}
  AIRFLOW_WWW_USER_PASSWORD: {{ .Values.airflow.webserver.password | quote }} 