apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flower
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.network.flower.port }}
      targetPort: flower
      protocol: TCP
      name: flower
  selector:
    {{- include "airflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker 