apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webserver
  namespace: {{ .Values.common.namespace }}
  labels:
    {{- include "airflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: webserver
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.network.webserver.port }}
      targetPort: web
      protocol: TCP
      name: web
  selector:
    {{- include "airflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webserver 